// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("675adfd0-980b-43ae-93f0-3f6fdec0ecba"),
	Geocodio("b7522fd3-706c-492d-b20c-7e8745b1f3cc"),
	LocationIQ("f8ff444b-8056-4432-aa3e-07cb04024fc6"),
	MapQuest("5cdb1183-b30b-4f2c-bd81-49b0e9409514");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
