// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twilioaccesstokengenerator.actions;

import com.twilio.jwt.accesstoken.AccessToken;
import com.twilio.jwt.accesstoken.VideoGrant;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * See https://www.twilio.com/docs/iam/access-tokens
 */
public class GenerateAccessToken extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String identity;
	private final java.lang.String twilioAccountSid;
	private final java.lang.String twilioApiKey;
	private final java.lang.String twilioApiSecret;

	public GenerateAccessToken(
		IContext context,
		java.lang.String _identity,
		java.lang.String _twilioAccountSid,
		java.lang.String _twilioApiKey,
		java.lang.String _twilioApiSecret
	)
	{
		super(context);
		this.identity = _identity;
		this.twilioAccountSid = _twilioAccountSid;
		this.twilioApiKey = _twilioApiKey;
		this.twilioApiSecret = _twilioApiSecret;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		VideoGrant grant = new VideoGrant();
		
		// Create access token
		AccessToken token = new AccessToken.Builder(
	      twilioAccountSid,
	      twilioApiKey,
	      twilioApiSecret.getBytes()
	    ).identity(identity).grant(grant).build();

		return(token.toJwt());
			  
			
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateAccessToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
